Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.boot_timeout = 600  # Augmenter le timeout
  
  machines = {
    "devops" => "192.168.56.10",
    "app" => "192.168.56.11",
    "db" => "192.168.56.12",
    "monitoring" => "192.168.56.13"
  }
  
  machines.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip
      
      machine.vm.provider "virtualbox" do |vb|
        vb.gui = true  # Activer temporairement pour voir ce qui se passe
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
      
      machine.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt install -y python3 python3-pip
      SHELL
    end
  end
end
